#!/bin/sh

set -x

trap "exit" INT TERM ERR

# start daemon
warp-svc --accept-tos > /dev/null &
sleep 1

if [ ! -f /var/lib/cloudflare-warp/reg.json ]; then
    warp-cli registration new && echo "Warp client registered!"
    # if a license key is provided, register the license
    if [ -n "$WARP_LICENSE" ]; then
        echo "License key found, registering license..."
        warp-cli registration license "$WARP_LICENSE" && echo "Warp license registered!"
    fi
    # if a custom endpoint is provided, set the custom endpoint
    if [ -n "$WARP_CUSTOM_ENDPOINT" ]; then
        echo "Custom endpoint found, setting custom endpoint..."
        warp-cli registration custom-endpoint "$WARP_CUSTOM_ENDPOINT" && echo "Warp custom endpoint set!"
    fi
    # connect to the warp server
    warp-cli mode proxy
    warp-cli proxy port 1081
    warp-cli connect
else
    echo "Warp client already registered, skip registration"
fi

exec socat tcp-listen:1080,reuseaddr,fork tcp:localhost:1081